/**
 * @file
 * DO NOT EDIT THIS FILE.
 * JavaScript for the Toast Messages module.
 */

(function ($, Drupal) {
  "use strict";

  function getToastMethod(type) {
    if (typeof iziToast === 'undefined') {
      return null;
    }

    if (typeof iziToast[type] === 'function') {
      return type;
    }

    return typeof iziToast.info === 'function' ? 'info' : null;
  }

  function toToastTypeFromDrupalMessage(element) {
    if (element.classList.contains('messages--error')) {
      return 'error';
    }
    if (element.classList.contains('messages--warning')) {
      return 'warning';
    }
    if (element.classList.contains('messages--status') || element.classList.contains('messages--ok')) {
      return 'success';
    }
    return 'info';
  }

  Drupal.behaviors.toastMessages = {
    attach: function (context, settings) {
      settings = settings || {};

      var $iziMessages = $(context)
        .find('div[data-izi-message]')
        .filter(function () {
          return this.dataset.iziProcessed !== '1';
        });

      var $drupalMessages = $(context)
        .find('[data-drupal-messages] .messages')
        .filter(function () {
          return this.dataset.iziProcessed !== '1';
        });

      // Support cases where behavior context itself is a messages wrapper.
      if (context.nodeType === 1) {
        if (context.matches && context.matches('div[data-izi-message]') && context.dataset.iziProcessed !== '1') {
          $iziMessages = $iziMessages.add(context);
        }
        if (context.matches && context.matches('[data-drupal-messages] .messages') && context.dataset.iziProcessed !== '1') {
          $drupalMessages = $drupalMessages.add(context);
        }
      }

      if (!$iziMessages.length && !$drupalMessages.length) {
        return;
      }

      function processMessages() {
        var processedAll = true;

        $iziMessages.each(function () {
          var currentValue = this;
          var iziType = currentValue.dataset.type || 'info';
          var toastMethod = getToastMethod(iziType);

          if (!toastMethod) {
            processedAll = false;
            return;
          }

          var iziSettings = Object.assign({}, settings.toastMessages || settings.iziMessage || {});

          iziToast[toastMethod](Object.assign(iziSettings, {
            allowHtml: true,
            title: currentValue.dataset.title || '',
            message: currentValue.innerHTML
          }));

          currentValue.dataset.iziProcessed = '1';
          currentValue.remove();
        });

        $drupalMessages.each(function () {
          var currentValue = this;
          var iziType = toToastTypeFromDrupalMessage(currentValue);
          var toastMethod = getToastMethod(iziType);

          if (!toastMethod) {
            processedAll = false;
            return;
          }

          var messagesList = [];
          $(currentValue).find('.messages__list > li').each(function () {
            messagesList.push(this.innerHTML);
          });

          if (!messagesList.length) {
            var content = $(currentValue).find('.messages__content').first();
            if (content.length) {
              messagesList.push(content.html());
            }
            else {
              messagesList.push(currentValue.innerHTML);
            }
          }

          messagesList.forEach(function (messageHtml) {
            var iziSettings = Object.assign({}, settings.toastMessages || settings.iziMessage || {});
            iziToast[toastMethod](Object.assign(iziSettings, {
              allowHtml: true,
              title: (toastMethod.charAt(0).toUpperCase() + toastMethod.slice(1)),
              message: messageHtml
            }));
          });

          currentValue.dataset.iziProcessed = '1';
          currentValue.remove();
        });

        return processedAll;
      }

      if (processMessages()) {
        return;
      }

      // Some browsers/extensions can delay script execution order.
      window.setTimeout(function () {
        if (processMessages()) {
          return;
        }

        $(context).find('[data-izi-messages]').each(function () {
          this.style.setProperty('display', 'block', 'important');
        });
      }, 100);
    }
  };
})(jQuery, Drupal);
