<?php

/**
 * @file
 * Contains update functions for the Toast Messages module.
 */

/**
 * Implements hook_requirements().
 */
function toast_messages_requirements($phase) {
  $requirements = [];

  if ($phase == 'install' || $phase == 'runtime') {
    $plugin_detected = file_exists(DRUPAL_ROOT . '/libraries/iziToast/dist/js/iziToast.min.js');

    if ($plugin_detected) {
      $requirements['toast_messages'] = [
        'title' => t('Toast Messages'),
        'value' => t('Library detected'),
        'severity' => REQUIREMENT_OK,
      ];
    }
    else {
      $requirements['toast_messages'] = [
        'title' => t('Toast Messages'),
        'value' => t('Library not detected'),
        'severity' => REQUIREMENT_ERROR,
        'description' => t('Before you can use the Toast Messages module, you need to download the iziToast library from github.com and place it in /libraries/iziToast. Check the README.md for more information. <a href=":plugin_url">Get the plugin here</a>.', [':plugin_url' => 'https://github.com/marcelodolza/iziToast']),
      ];
    }
  }

  return $requirements;
}
