<?php

/**
 * @file
 * Defines the hooks for the Toast Messages custom module.
 */

use Drupal\toast_messages\Utility\HelpTemplate;

/**
 * Implements hook_help().
 */
function toast_messages_help($route_name, $route_match) {
  if ($route_name === 'help.page.toast_messages') {
    $readmy = file_get_contents(__DIR__ . '/README.md');
    if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
      $template = HelpTemplate::help();
      return \Drupal::service('renderer')->render($template);
    }
    else {
      $filter_manager = \Drupal::service('plugin.manager.filter');
      $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
      $config = ['settings' => $settings];
      $filter = $filter_manager->createInstance('markdown', $config);
      return $filter->process($readmy, 'en');
    }
  }
  return NULL;

}

/**
 * Implements hook_page_attachments().
 */
function toast_messages_page_attachments(array &$attachments) {
  $config = \Drupal::config('toast_messages.settings')->get();
  if (!empty($config['_core'])) {
    unset($config['_core']);
  }

  $attachments['#attached']['library'][] = 'toast_messages/toast_messages';
  $attachments['#attached']['drupalSettings']['toastMessages'] = $config;
}

/**
 * Implements hook_preprocess_hook().
 */
function toast_messages_preprocess_page(&$variables) {
  $config = \Drupal::config('toast_messages.settings')->get();
  if (!empty($config['_core'])) {
    unset($config['_core']);
  }
  $variables['#attached']['drupalSettings']['toastMessages'] = $config;
}

/**
 * Implements hook_theme().
 */
function toast_messages_theme($existing, $type, $theme, $path) {
  return [
    'toast_messages' => [
      'render element' => 'element',
      'variables' => [
        'children' => '',
        'message_list' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_element_info_alter().
 */
function toast_messages_element_info_alter(array &$info) {
  $info['status_messages']['#pre_render'] = ['\Drupal\toast_messages\ToastMessages::generatePlaceholder'];
}
